- name: Create startup folder
  ansible.builtin.file:
    path: "/cron"
    state: directory

- name: Remove cron file scripts
  file:
    path: '{{item}}'
    state: absent
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Create cron file sripts
  ansible.builtin.file:
    path: '{{item}}'
    state: touch
    mode: u+rw,g-wx,o-rwx
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Make Scripts Executable
  file: dest={{item}} mode=a+x
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Write Cron Job docker cleanup
  lineinfile: 
    dest: "/cron/weekly_job.sh"
    line: '{{ item }}'
  with_items:
    - 'docker system prune -af'

- name: Create crontab for docker image prune
  ansible.builtin.cron:
    name: "Swarm job for docker image/volume cleanup"
    special_time: daily
    job: "bash /cron/weekly_job.sh /cron/weekly_job.log 2>&1"