- name: Enable UFW and deny all by default
  ufw:
    state: enabled
    policy: allow

- name: Set logging
  ufw:
    logging: 'on'

- ufw:
    rule: allow
    name: OpenSSH

# swarm ports

- name: Open NGINX ports
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80' 
    - '443'
    
- name: Allow port range 8079-8090 (App Range)
  ufw:
    rule: allow
    port: 8079:8098
    proto: tcp

- name: Open Swarm Ports TCP
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '4789' 
    - '7946'
    - '4098' #db-network  
    - '4097' #container-swarm-network
    - "4099" #portainer-agent-network
    - '2377' #swarm
    - '3306' #mysql
    - '8080' #rancher
    - '9345' #rancher
    - '5432' #postgres

- name: Open Swarm Ports UDP
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items:
    - '4789' 
    - '7946'
    - '4098' #db-network  
    - '4097' #container-swarm-network
    - "4099" #portainer-agent-network
    - '2377' #swarm
    - '3306' #mysql
    - '8080' #rancher
    - '9345' #rancher
    - '5432' #postgres
