- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes
    